name: TF Docs Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - ./proxmox/vm
      - ./proxmox/lxc
      - ./proxmox/cloud-img-download

jobs:
  generate-docs:
    runs-on: self-hosted
    strategy:
      matrix:
        module:
          - path: "./proxmox/vm"
            name: "vm"
          - path: "./proxmox/lxc"
            name: "lxc"
          - path: "./proxmox/cloud-img-download"
            name: "cloud-img"
    container:
      image: ghcr.io/tinycloud-labs/tf-tools:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Git Setup
        uses: ./.github/actions/setup-git
        with:
          repo-path: /__w/proxmox-tf-modules/proxmox-tf-modules

      - name: Fetch latest changes
        run: |
          git config --global pull.rebase false
          git fetch origin ${{ github.head_ref }}
          git pull origin ${{ github.head_ref }}

      - name: Generate Docs
        run: |
          terraform-docs markdown document ${{ matrix.module.path }} --output-file README.md --output-mode inject

      - name: Upload generated docs
        uses: actions/upload-artifact@v4
        with:
          name: generated-docs-${{ matrix.module.name }}
          path: ${{ matrix.module.path }}/README.md

  commit-changes:
    runs-on: ubuntu-latest
    needs: generate-docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Git Setup
        uses: ./.github/actions/setup-git
        with:
          repo-path: /__w/proxmox-tf-modules/proxmox-tf-modules

      - name: Download all docs
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Move generated README.md files to module directories
        run: |
          mv ./artifacts/generated-docs-vm/README.md ./proxmox/vm/README.md
          mv ./artifacts/generated-docs-lxc/README.md ./proxmox/lxc/README.md
          mv ./artifacts/generated-docs-cloud-img/README.md ./proxmox/cloud-img-download/README.md

      - name: Commit changes
        run: |
          git add -A
          git commit -m "chore: update Terraform docs [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
