name: VM Module Smoke Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'proxmox/vm/**'

jobs:
  smoke-test:
    runs-on: self-hosted
    container:
      image: ghcr.io/stackgarage/tf-tools:latest
    env:
      TF_VAR_api_token: ${{ secrets.PROXMOX_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run Git Setup
        uses: ./.github/actions/setup-git
        with:
          repo-path: /__w/proxmox-tf-modules/proxmox-tf-modules

      - name: Fetch latest changes
        run: |
          git fetch origin ${{ github.head_ref }}
          git pull origin ${{ github.head_ref }}

      - name: Generate VM smoke test Terraform file
        run: |
          cat <<EOF >> ./test/main.auto.tf
          module "smoke_test" {
            source              = "git::https://github.com/shakir85/terraform_modules.git//proxmox/vm?ref=${BRANCH_NAME}"
            proxmox_node_name   = "pve1"
            disk_name           = "sdc"
            ssh_public_key_path = "\${path.module}/id_rsa.pub"
            username            = random_pet.name.id
            hostname            = "smoke-test-\${random_pet.name.id}"
            timezone            = "Etc/UTC"
            cloud_image_info    = ["sdc", "debian-12-generic-amd64.qcow2.img"]
            disk_size           = "20"
            memory              = 1028
            depends_on          = [local_file.public_key]
          }
          EOF
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./test

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./test
